n_train_sims: 3 # number of simulations per rounds
datadir: "results/gammaDFE_cnst_N_sfs/data/"
posteriordir: "results/gammaDFE_cnst_N_sfs/posterior/"
demog_model: "gammaDFE_cnst_N"
ts_processor: "tskit_sfs_selection"
n_snps: 2000 # number of SNPs to use (for dinf)
embedding_net: "MLP"
total_rounds: 3 # number of rounds
N: 100 # population size