# --- top level arguments are ALWAYS REQUIRED --- #

# change this to the project directory you want to use
project_dir: "/home/adkern/popgensbi_snakemake/recombination_rate"

cpu_resources:
  runtime: "2h"
  mem_mb: 16000

gpu_resources: 
  runtime: "4h"
  mem_mb: 50000
  gpus: 1
  slurm_partition: "kerngpu,gpu"
  slurm_extra: "--gres=gpu:1 --constraint=a100"

random_seed: 1
chunk_size: 10 # number of instances to simulate per worker
n_train: 1000
n_val: 100
n_test: 100

train_embedding_net_separately: True # train embedding network separately from normalizing flow
use_cache: True # load features into CPU memory
optimizer: "Adam"
batch_size: 32
learning_rate: 0.0005
max_num_epochs: 200
stop_after_epochs: 20
clip_max_norm: 5
packed_sequence: True

simulator:
  class_name: "recombination_rate"
  # OPTIONAL CLASS KWARGS:
  sequence_length: 2000000
  mutation_rate: 1.5e-8
  pop_size: 1e4
  samples:
    0: 20

processor:
  class_name: "genotypes_and_distances"
  # OPTIONAL CLASS KWARGS:
  n_snps: 2000
  maf_thresh: 0.05

embedding_network:
  class_name: "RNN"
  # OPTIONAL CLASS KWARGS:
  input_size: 21 # num individuals + 1
  output_size: 64

